### ISSUE TITLE
Render from inventory

### ISSUE THREAD

**Issue by mat-1** [AterAnimAvis/BlockRenderer#23]
You should be able to click the render key while hovering the mouse over an item in inventories to render an item. I need this to be able to render items from OriginRealms (play.originrealms.com), a server which adds custom items with a resource pack that applies to vanilla items with certain NBT tags (most custom items use paper).

At the moment I have to obtain the item and hold it to render the item, but this is kind of tedious. I can't use the bulk renderer since that just renders the vanilla items.

Here's a screenshot that shows some of the items that exist.
![Custom items](https://user-images.githubusercontent.com/27899617/106796420-ee6c6580-6620-11eb-883a-5dd6dbd8b452.png)

**Comment by AterAnimAvis** [comment]
Unless I broke something this should still be a feature, hovering over an item and pressing the render key should work. 

Unfortunately due to the way Minecraft Screens work this may not work for all inventories or if you have the RecipeBook open.

I will re-test this functionality when I get a chance.

**Comment by mat-1** [comment]
Oh disabling the recipe book fixed it
